### ISSUE TITLE
Context menu entry on solution would be nice to have

### ISSUE THREAD

**Issue by iFedaka** [mrlacey/DontCopyAlways#1]
Usually I open whole solution with bunch of projects.
Since I don't know which project has offending "Copy always", I'd need to manually go through each project file.

**Comment by mrlacey** [comment]
That seems like a very good idea. ;)

**Comment by mrlacey** [comment]
Version 1.1 has just been uploaded to the marketplace and includes this ability. 🎉

Show your appreciation by [leaving a rating/review in the marketplace](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.DontCopyAlways&ssr=false#review-details) and a star on this repo. 😃
