### ISSUE TITLE
Write files with BOM.

### ISSUE THREAD

**Issue by jvsca** [mrlacey/DontCopyAlways#4]
The extension saves the files as UTF-8, instead of UTF-8-BOM.

Comparing the files result in:
"These files have different encodings. Left file: Unicode (UTF-8) with signature. Right file: Unicode (UTF-8) without signature. You can resolve the difference by saving the right file with the encoding Unicode (UTF-8) with signature."

Options:
1- Add the encoding to File.WriteAllText(), to always save with BOM (Text.Encoding.UTF8).
2- Add one option to the extension to save with/without BOM.
3- Detect the encoding of the original file and preserve it on save.

**Comment by mrlacey** [comment]
This is a great suggestion.

_(Note to self: check other extensions that write XML files.)_

**Comment by mrlacey** [comment]
> 3- Detect the encoding of the original file and preserve it on save.

I've gone for this option

**Comment by jvsca** [comment]
Good choice. The options are in order of difficult level, easier to harder.

**Comment by mrlacey** [comment]
This functionality has been incorporated into version 1.2 and is now available from the marketplace.

Please show your support and appreciation by leaving a rating/review: https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.DontCopyAlways&ssr=false#review-details

Thanks.
